SET FOREIGN_KEY_CHECKS = 0;

-- ==========================================
-- 1. TẠO CẤU TRÚC BẢNG (SCHEMA)
-- ==========================================

-- Tạo bảng: classanimals (Các lớp động vật)
CREATE TABLE IF NOT EXISTS `classanimals` (
  `id_class` INT AUTO_INCREMENT PRIMARY KEY,
  `background_video` VARCHAR(255) NULL,
  `info` TEXT NULL,
  `name` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng: animals (Danh sách các loài động vật)
CREATE TABLE IF NOT EXISTS `animals` (
  `id_animal` INT AUTO_INCREMENT PRIMARY KEY,
  `avatar` VARCHAR(255) NULL,
  `gioi_thieu_text` TEXT NULL,
  `imgqr3d` VARCHAR(255) NULL,
  `ngoai_hinh_text` TEXT NULL,
  `noi_sinh_song_image` VARCHAR(255) NULL,
  `noi_sinh_song_text` TEXT NULL,
  `name` VARCHAR(255) NOT NULL,
  `classanimals_id` INT NOT NULL,
  CONSTRAINT `fk_animals_class` FOREIGN KEY (`classanimals_id`) REFERENCES `classanimals` (`id_class`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng: listanimals (Hình ảnh chi tiết các loài)
CREATE TABLE IF NOT EXISTS `listanimals` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `animalimage` VARCHAR(255) NULL,
  `animals_id` INT NOT NULL,
  CONSTRAINT `fk_listanimals_animals` FOREIGN KEY (`animals_id`) REFERENCES `animals` (`id_animal`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng: user (Thành viên)
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(50) NULL,
  `provider` VARCHAR(255) NULL,
  `username` VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng: role (Vai trò hệ thống)
CREATE TABLE IF NOT EXISTS `role` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `description` TEXT NULL,
  `name` VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng: user_role (Liên kết thành viên và vai trò)
CREATE TABLE IF NOT EXISTS `user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_user_role_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_role_role` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng: posts (Bài viết diễn đàn)
CREATE TABLE IF NOT EXISTS `posts` (
  `id_post` INT AUTO_INCREMENT PRIMARY KEY,
  `date` DATETIME NOT NULL,
  `image` VARCHAR(255) NULL,
  `title` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  CONSTRAINT `fk_posts_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng: comments (Bình luận bài viết)
CREATE TABLE IF NOT EXISTS `comments` (
  `id_cmt` INT AUTO_INCREMENT PRIMARY KEY,
  `chat_data` TEXT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  CONSTRAINT `fk_comments_posts` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id_post`) ON DELETE CASCADE,
  CONSTRAINT `fk_comments_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng: notifications (Log thông báo admin)
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `type` VARCHAR(50) NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `message` TEXT NULL,
  `link` VARCHAR(255) NULL,
  `target_type` VARCHAR(50) NULL,
  `target_id` VARCHAR(50) NULL,
  `actor_id` INT NULL,
  `actor_name` VARCHAR(255) NULL,
  `actor_roles` VARCHAR(255) NULL,
  `meta_json` LONGTEXT NULL,
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_notifications_created_at` (`created_at`),
  INDEX `idx_notifications_is_read` (`is_read`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- 2. NHẬP DỮ LIỆU (DATA IMPORT)
-- ==========================================

-- Thêm dữ liệu mẫu: Các vai trò hệ thống
INSERT IGNORE INTO `role` (`id`, `name`, `description`) VALUES
(1, 'ADMIN', 'Quản trị viên hệ thống'),
(2, 'USER', 'Thành viên cộng đồng');

-- Thêm dữ liệu mẫu: Tài khoản Admin mặc định (Username: admin, Password: admin123)
INSERT IGNORE INTO `user` (`id`, `email`, `password`, `phone`, `provider`, `username`) VALUES
(1, 'admin@nekopara.com', '$2y$10$7BA6/7/3fyl1UyLTQ9hfBOl72an1hcYEE0o5d0spzqVxtKaHTHsOa', '0123456789', 'local', 'admin');

-- Gán vai trò ADMIN cho tài khoản admin
INSERT IGNORE INTO `user_role` (`user_id`, `role_id`) VALUES
(1, 1);

-- INSERT IGNORE classanimals
INSERT IGNORE INTO `classanimals` (`id_class`, `name`, `info`, `background_video`) VALUES (1, 'Động vật bò sát', 'Động vật bò sát là một nhóm động vật thuộc lớp Reptilia trong hệ thống phân loại động vật.Đặc điểm chung của các động vật bò sát là chúng có da vảy và hệ tuần hoàn xanh, cơ thể chia thành đầu, thân và đuôi.Động vật bò sát có phạm vi sinh sống rất rộng, từ vùng cận nhiệt đới đến cực bắc và cực nam trên Trái Đất.', 'dongvatbosat.gif');
INSERT IGNORE INTO `classanimals` (`id_class`, `name`, `info`, `background_video`) VALUES (2, 'Cá', 'Cá là một nhóm động vật thuộc lớp Pisces trong hệ thống phân loại động vật. Cá có phần lớn sống trong môi trường nước và có khả năng di chuyển bằng cách lội, bơi, hoặc sử dụng vây và vây đuôi.Chúng có cấu trúc cơ thể được bao bọc bởi vảy, có vây và mang để tham gia vào quá trình hô hấp.Cá là nhóm động vật nổi tiếng với sự đa dạng về hình dáng, kích thước và màu sắc.', 'ca.gif');
INSERT IGNORE INTO `classanimals` (`id_class`, `name`, `info`, `background_video`) VALUES (3, 'Chim', 'Chim là một nhóm động vật thuộc lớp Aves trong hệ thống phân loại động vật. Chúng là những sinh vật có xương sống, có lông và đẻ trứng.Chim có cấu trúc cơ thể được thiết kế để bay với cánh và lông ngoài trừ một số loài chim đặc biệt khác.Lớp chim dược chia làm 3 nhóm là chim chạy,chim bơi và chim bay.', 'chim.gif');
INSERT IGNORE INTO `classanimals` (`id_class`, `name`, `info`, `background_video`) VALUES (4, 'Động vật có vú', 'Động vật có vú là một nhóm động vật thuộc lớp Mammalia trong hệ thống phân loại động vật. Đặc điểm chung của các loài động vật có vú là chúng có xương sống có vú, có lông và có tuyến sữa để nuôi con non.Động vật có vú rất đa dạng về hình dáng, kích thước và cách sống. Chúng sống trên khắp các môi trường trên Trái Đất từ đại dương, rừng nhiệt đới, đồng cỏ, sa mạc cho đến khu vực cận cực.', 'dongvatcovu.gif');
INSERT IGNORE INTO `classanimals` (`id_class`, `name`, `info`, `background_video`) VALUES (5, 'Động vật không xương sống', 'Động vật không xương sống là một nhóm động vật không có xương sống trong hệ thống phân loại động vật. Thay vì có xương sống, chúng có cấu trúc cơ thể linh hoạt và hỗn hợp, thường được hỗ trợ bởi hệ cơ và xoắn cơ. Nhóm động vật không xương sống rất đa dạng và bao gồm các nhóm như động vật thân mềm,động vật giun,động vật giáp xác và nhiều nhóm khác.', 'dongvatkhongxuongsong.gif');
INSERT IGNORE INTO `classanimals` (`id_class`, `name`, `info`, `background_video`) VALUES (6, 'Động vật lưỡng cư', 'Động vật lưỡng cư là một nhóm động vật thuộc lớp Amphibia trong hệ thống phân loại động vật.Tên gọi lưỡng cư xuất phát từ khả năng của chúng có thể sống cả trên cạn và trong nước.Đặc điểm chung của động vật lưỡng cư là chúng có da mỏng và ẩm, không có lớp biểu bì chất kháng nước như động vật bò sát hay chim. Chúng có cấu trúc da đặc biệt để hấp thụ nước và chất dinh dưỡng từ môi trường xung quanh.', 'dongvatluongcu.gif');

-- INSERT IGNORE animals
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (1, 'Cá sấu', 'Cá sấu được coi là một trong những loài động vật ăn thịt nguy hiểm,chúng là những kẻ săn mồi giỏi, có khả năng nhanh nhẹn trong nước và biết cách tấn công bất ngờ. Ngoài ra, cá sấu cũng rất kiên cường và có khả năng thích ứng cao, có thể sống sót qua nhiều thời kỳ địa chất khác nhau.', 'Cá sấu có một cơ thể to lớn, lông nhẵn, với một cái đầu rộng và cái miệng đầy răng nhọn. Chúng có một cái đuôi dài và mạnh dùng để bơi. Chân trước có móng vuốt sắc để bám vào mồi và chân sau dẹt dùng để bơi. Cá sấu có thể lên tới 6 mét chiều dài và nặng đến 1 tấn.', 'Cá sấu sinh sống ở các vùng rừng ngập nước, ven sông, hồ và đầm lầy ở nhiệt đới và cận nhiệt đới. Chúng phân bố chủ yếu ở Châu Phi, Châu Á, Úc và Mỹ Latinh. Một số loài cá sấu quý hiếm chỉ còn sống ở một số khu vực hẹp.', 'casauAvatar.jpg', 'casauNSS.png', 'casauQR.png', 1);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (2, 'Thằn lằn', 'Thằn lằn là loài động vật bò sát phổ biến trên toàn thế giới, nổi bật với khả năng thay đổi màu sắc da, đuôi linh hoạt và móng vuốt sắc bén giúp chúng di chuyển và săn mồi dễ dàng. Đôi tai lớn và nhạy cảm của chúng giúp phát hiện âm thanh và nguy hiểm.Sự thích ứng với nhiều môi trường sống khác nhau làm cho chúng trở thành một phần không thể thiếu trong hệ sinh thái.', 'Thằn lằn là một loài động vật bò sát có hình dáng phẳng và dẹp, thường có bốn chân và đuôi dài. Da của chúng thường mảnh và có thể thay đổi màu sắc để phản ánh môi trường xung quanh.', 'hằn lằn sống chủ yếu ở các môi trường khô ráo như sa mạc, thảo nguyên và khu rừng xerophytic. Tùy theo loài, chúng có thể được tìm thấy ở nhiều khu vực trên khắp thế giới như: Châu Phi, Châu Mỹ, Úc, Đại Tây Dương,...', 'thanlanAvatar.jpg', 'thanlanNSS.png', 'thanlanQR.png', 1);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (3, 'Rắn', 'Rắn là nhóm động vật bò sát không chân và thường có cơ thể dẹp và dài. Chúng có hệ thống cảm giác phát triển, bao gồm lưỡi và cơ quan Jacobson để phát hiện mùi hương và hương vị. Rắn di chuyển bằng cách lùi hoặc nắm bám và thường săn mồi bằng cách nuốt chửng hoặc hạ gục bằng nọc độc. Với khoảng 3,000 loài phân bố trên khắp thế giới, rắn đóng vai trò quan trọng trong các hệ sinh thái', 'Rắn thường có cơ thể dài và mảnh mai, không chân và không cánh, với đầu nhỏ và thân trụ. Da của rắn được phủ bởi vảy, giúp bảo vệ và giảm ma sát khi di chuyển.', 'Rắn sống chủ yếu trong các môi trường đa dạng từ khu rừng nhiệt đới đến sa mạc khô cằn và núi cao. Chúng cũng có thể được tìm thấy ở hầu hết các nước trên thế giới như :Brazil,Ấn Độ, Châu Á,...', 'ranAvatar.jpg', 'ranNSS.png', 'ranQR.png', 1);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (4, 'Cá ngừ', 'Cá ngừ có khả năng duy trì nhiệt độ cơ thể cao, cho phép chúng hoạt động hiệu quả trong các vùng biển lạnh. Cá ngừ thường di chuyển nhanh và là loài săn mồi khá thành công, thường săn mồi trong các đàn lớn và sử dụng tốc độ để vượt qua các con mồi.', 'Cá ngừ là một loại cá biển có hình dáng mảnh mai và thon dài, thường có thân hình mạnh mẽ và chắc chắn. Da của chúng thường được phủ bởi vảy nhỏ và mượt mà. Mắt của cá ngừ thường lớn và sáng bóng, giúp chúng tìm kiếm mồi trong đại dương sâu. Đặc biệt, cá ngừ có một dãy vây lưng và vây bụng, cùng với các đuôi vây dài và linh hoạt.', 'Cá ngừ thường sinh sống ở các khu vực biển nhiệt đới và cận nhiệt đới trên khắp thế giới. Chúng thường xuất hiện ở các vùng biển sâu. Một số khu vực phổ biến cho cá ngừ như: các vùng biển xung quanh Hawaii, Đại Tây Dương, Biển Địa Trung Hải và vùng biển ngoài khơi của Nhật Bản.', 'canguAvatar.jpg', 'canguNSS.png', 'canguQR.png', 2);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (5, 'Cá mập', 'Cá mập được biết đến với hàm răng sắc bén và mạnh mẽ, được sắp xếp thành hàng để giúp trong việc săn mồi và ăn thức ăn. Hàm răng của cá mập là một trong những điểm đặc trưng quan trọng của chúng, cho phép chúng xé nát và tiêu hóa thức ăn một cách hiệu quả.', 'Cá mập có hình dạng thon dài và thân được bao phủ bởi lớp da sần sùi và thô ráp. Màu sắc thân cá mập thường là xám hoặc xanh đậm, giúp chúng hòa trộn tốt với môi trường nước xung quanh.', 'Cá mập phân bố rộng khắp trên toàn thế giới, từ các vùng biển nhiệt đới đến cực lạnh. Chúng thường sống ở vùng nước sâu, nhưng cũng có thể xuất hiện gần bờ biển và trong các khu vực ngập nước, là một phần quan trọng của hệ sinh thái đại dương.', 'camapAvatar.jpg', 'camapNSS.png', 'camapQR.png', 2);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (6, 'Cá lóc', 'Cá lóc là loài có khả năng thích nghi và sinh tồn trong các môi trường sống khắc nghiệt. Chúng có thể tồn tại trong những vùng nước cạn, ô nhiễm và thiếu ôxy bằng cách hô hấp qua da và các mào mang. Cá lóc cũng rất hung dữ và săn mồi bằng cách tấn công nhanh chóng với hàm răng sắc nhọn. Chúng là những kẻ săn mồi nguy hiểm đối với nhiều loài thủy sinh khác.', 'Cá lóc có thân dài, hơi dẹp và lithe. Da cá có màu nâu xám hoặc xanh lục ở lưng, phía bụng trắng hoặc vàng nhạt. Đầu cá nhỏ, mõm nhọn, miệng rộng với hàm răng sắc nhọn. Vây lưng, vây hậu môn và vây đuôi của cá lóc rất dài và có màu đen. Cá lóc có khả năng cứng cáp và linh hoạt, có thể di chuyển nhanh chóng.', 'Cá lóc thường sống ở vùng nước ngọt như sông, hồ, ao, đầm lầy ở nhiều nơi trên thế giới, đặc biệt phổ biến ở châu Á. Chúng ưa những vùng nước yên tĩnh, có nhiều thực vật và ẩn nấp. Cá lóc thường trốn ẩn dưới bùn, cát và cỏ dưới nước để chờ đợi mồi.', 'CaLocAvatar.jpg', 'calocNSS.png', 'calocQR.png', 2);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (7, 'Chim cánh cụt', 'Chim cánh cụt là loài chim không thể bay nhưng lại có khả năng bơi lội rất giỏi trong nước. Chúng được coi là những chuyên gia của thế giới nước, thích nghi tốt với môi trường đầy băng tuyết của vùng cực.', 'Chim cánh cụt có vóc dáng thân hình hơi tròn, chân ngắn và mặt có mào lông. Lông của chim cánh cụt thường có màu đen, trắng hoặc xám, giúp chúng hòa trộn với môi trường băng tuyết xung quanh. Chúng cũng có cánh ngắn hình thước, phát triển thành vây bơi lội.', 'Chim cánh cụt sống chủ yếu ở các vùng cực lạnh của Nam Cực và Bắc Cực, nơi mà băng tuyết và nước biển đóng băng. Chúng tập trung sinh sống và giao phối trên mặt đất băng, và thường săn mồi dưới nước để kiếm sống. Chim cánh cụt là một trong những loài động vật biển đặc biệt, thích nghi tốt với môi trường khắc nghiệt của vùng cực.', 'chimcanhcutAvatar.jpg', 'chimcanhcutNSS.png', 'chimcanhcutQR.png', 3);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (8, 'Đại bàng', 'Đại bàng là loài chim săn mồi có thị giác rất tốt, có khả năng nhìn rõ từ khoảng cách xa và giữ được ánh mắt tròn lớn, sắc bén. Chúng sử dụng thị giác tuyệt vời này để tìm kiếm mồi và tiến hành các cuộc săn mồi hiệu quả.', 'Đại bàng có kích thước vừa đến lớn, thường có cánh rộng và đuôi dài. Lông của đại bàng thường là màu nâu hoặc xám, với phần đầu và cổ có lông màu trắng hoặc nâu đậm. Chúng có đôi mắt lớn và sắc bén, giúp cho việc săn mồi trong không gian rộng lớn.', 'Đại bàng phân bố khắp các vùng lục địa trên thế giới, từ các khu rừng nhiệt đới đến vùng sa mạc và núi non. Chúng thường sống ở những khu vực có nguồn lương thực dồi dào và có nhiều mồi để săn.', 'daibangAvatar.jpg', 'daibangNSS.png', 'daibangQR.png', 3);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (9, 'Bồ nông', 'Bồ nông là loài có khả năng lặn và bắt mồi dưới nước. Chúng có thể lặn rất sâu và nhanh chóng bắt được con mồi bằng mỏ nhọn. Bồ nông cũng là loài chim rất lanh lẹ, linh hoạt và biết lợi dụng các điều kiện tự nhiên để săn mồi. Ngoài ra, bồ nông thường sống thành đàn, hợp tác săn mồi và bảo vệ lãnh thổ.', 'Bồ nông là một loài chim ăn cá nhỏ với thân hình dài, mỏ nhọn và chân ngắn. Lông của bồ nông có màu đen, trắng và xám, giúp chúng hòa vào môi trường sống. Mỏ bồ nông thon dài và sắc nhọn, rất thích hợp để săn bắt các loài cá nhỏ. Chân ngắn nhưng chắc khỏe giúp chúng di chuyển linh hoạt trên mặt nước.', 'Bồ nông thường sống ở các vùng ven biển, ven hồ, sông ngòi có nhiều cá. Chúng thích những khu vực nước cạn, ít sâu để dễ dàng tìm kiếm và bắt mồi. Các loài bồ nông có thể tìm thấy ở khắp châu Âu, châu Á và Bắc Mỹ.', 'bonongAvatar.jpg', 'bonongNSS.png', 'bonongQR.png', 3);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (10, 'Hổ', 'Hổ là loài có sức mạnh phi thường và bản tính hung dữ. Chúng là động vật ăn thịt, săn mồi bằng kỹ năng mai phục và tấn công bất ngờ. Hổ có thể xé xác mồi bằng móng vuốt và hàm răng sắc nhọn. Ngoài ra, hổ cũng rất thông minh, có khả năng tính toán và triển khai chiến lược săn mồi tinh vi. Tiếng gầm của hổ cũng là một trong những âm thanh đáng sợ nhất trong tự nhiên.', 'Hổ là một trong những loài động vật có vú lớn nhất trên thế giới. Chúng có bộ lông ngắn, mượt và sọc đen vằn vào nền lông vàng cam. Đầu hổ to, có hàm răng sắc nhọn và móng vuốt sắc bén. Chân hổ to, khỏe và rất linh hoạt. Kích thước cơ thể hổ có thể lên tới 3,3 mét và nặng tới 300 kg.', 'Hổ chủ yếu sinh sống ở các khu rừng nhiệt đới và ôn đới của châu Á, từ Siberia đến Sumatra. Chúng thích những khu rừng rậm, núi non và thung lũng có nguồn nước. Hổ sống độc lập và lãnh thổ, thường kiểm soát một vùng rộng lớn để săn mồi.', 'HoAvatar.jpg', 'hoNSS.png', 'hoQR.png', 4);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (11, 'Gấu', 'Gấu là loài có sức mạnh, tính cách hung dữ nhưng cũng rất thông minh. Chúng có bộ vuốt sắc nhọn và răng cực kỳ sắc bén, được dùng để tự vệ và săn mồi. Gấu cũng là loài động vật có kích cỡ cơ thể lớn, có thể đập bẹp các đối thủ bằng sức mạnh. Ngoài ra, gấu còn biết trèo cây, bơi lội giỏi và thích lăn lê trên đất.', 'Gấu là một trong những loài động vật có vú lớn nhất. Chúng có cơ thể to lớn, chắc khỏe, với bộ lông dày và mềm mại. Gấu có đầu to, mõm ngắn, tai nhỏ tròn và chân to khỏe. Tùy theo từng loài, màu sắc lông của gấu có thể từ đen, nâu, trắng đến vàng.', 'Gấu có thể sống ở nhiều môi trường khác nhau, từ rừng rậm, núi cao đến các vùng đồng cỏ và sa mạc.Một số loài gấu như gấu Bắc Cực thích sống ở vùng Bắc Cực lạnh giá, trong khi gấu Brun thường sống ở những cánh rừng ôn đới.', 'GauAvatar.jpg', 'gauNSS.png', 'gauQR.png', 4);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (12, 'Hươu cao cổ', 'Hươu cao cổ có khả năng quan sát và phát hiện mối nguy hiểm từ xa nhờ cái cổ dài của mình. Chúng có thể quan sát và cảnh báo đàn về sự xuất hiện của các loài động vật săn mồi lớn. Ngoài ra, cái cổ dài cũng giúp chúng dễ dàng với tới những nhánh cây cao, lá non và những nguồn thức ăn khó tiếp cận đối với các động vật khác.', 'Hươu cao cổ là loài động vật có vú có bộ xương lớn nhất trong các loài động vật. Đặc biệt chúng có chiếc cổ siêu dài, có thể lên tới 2,4 mét. Đầu của hươu cao cổ tương đối nhỏ, có những chiếc sừng nhỏ mọc lên từ đỉnh đầu. Chân của chúng rất dài và mảnh, kết hợp với cái cổ dài giúp hươu cao cổ có thể với tới những nhánh cây cao.', 'Hươu cao cổ chủ yếu sinh sống ở các vùng đất cằn cỗi, khô hạn của châu Phi, như sa mạc, bán sa mạc và các thảo nguyên rộng lớn. Chúng thích những khu vực có nhiều cây ăn lá, đặc biệt là các loài cây cao và khô như cây lá kim. Hươu cao cổ di chuyển theo đàn, trú ẩn và kiếm ăn ở những vùng đất rộng mở.', 'HuoucaocoAvatar.jpg', 'huoucaocoNSS.png', 'huoucaocoQR.png', 4);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (13, 'Sứa', 'Sứa là loài có  khả năng di chuyển linh hoạt trong môi trường nước bằng cách đẩy nước ra từ các túi nước nhỏ ở phía dưới cơ thể. Chúng có các cơ quan giác quan đặc biệt để phát hiện ánh sáng, mùi vị và chuyển động trong nước.', 'Sứa có hình dạng phẳng và trong suốt, thường có màu sắc như xanh lam, đỏ hoặc trắng. Chúng có cấu trúc dẹt và rộng, thường có các cánh vây phát ra từ trung tâm. Sứa không có hệ xương, mà chúng được hỗ trợ bởi một khung xương dẻo bên trong', 'Sứa thường sinh sống ở các vùng biển và đại dương trên toàn thế giới, trong đó có các khu vực nước nông và nước sâu. Chúng thường được tìm thấy ở gần bờ biển, gần các rạn san hô và ở các khu vực nước lặn thấp.', 'suaAvatar.jpg', 'suaNSS.png', 'suaQR.png', 5);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (14, 'Bạch tuột', 'Bạch tuột là loài có khả năng thay đổi màu sắc da một cách nhanh chóng để hòa vào môi trường xung quanh. Chúng có thể chuyển từ màu trắng sang màu sẫm trong vòng vài giây để trốn tránh kẻ thù hoặc săn mồi. Bạch tuột cũng có thể phun ra một chất dịch màu đen để làm mờ tầm nhìn của kẻ thù khi cảm thấy nguy hiểm.', 'Bạch tuột có một cơ thể mềm mại, không xương và thường được bao phủ bởi một lớp da mỏng. Chúng có tám chân và một đầu lớn với những chiếc càng dài và linh hoạt. Màu sắc của bạch tuột có thể thay đổi từ trắng, hồng đến xám đen hoặc nâu, điều này giúp chúng dễ dàng ẩn náu trong môi trường sống.', 'Bạch tuột thường sinh sống ở các vùng biển nông, gần bờ biển, trong các rạn san hô hoặc dưới các tảng đá lớn. Chúng thích những vùng nước ấm, nhiều thực vật và đầy ắp những hang động nhỏ để trú ẩn. Một số loài bạch tuột sống ở độ sâu hàng trăm mét dưới đáy biển.', 'BachtuotAvatar.jpg', 'bachtuotNSS.png', 'bachtuotQR.png', 5);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (15, 'Tôm', 'Tôm là loài có khả năng di chuyển nhanh nhờ vào những cú đập mạnh của đuôi. Khi cảm thấy nguy hiểm, tôm có thể bơi lùi rất nhanh để tránh kẻ thù. Ngoài ra, lớp vỏ cứng của tôm cũng là một lá chắn tự nhiên giúp chúng bảo vệ mình khỏi các mối đe dọa.', 'tôm là loài động vật giáp xác có một cơ thể mềm mại được bao phủ bởi một lớp vỏ cứng và bền chắc. Chân và càng của tôm thường dài và gắn liền với thân, giúp chúng di chuyển linh hoạt dưới nước. Màu sắc của tôm rất đa dạng, từ đỏ, hồng, xanh đến trong suốt, tùy thuộc vào từng loài.', 'Tôm thường sống ở những vùng nước biển, như đại dương, vịnh, ven bờ và cả nước ngọt như sông, hồ. Chúng tìm kiếm thức ăn và trú ẩn giữa các rạn san hô, bãi cỏ biển hoặc dưới các tảng đá. Một số loài tôm sống trong hang động dưới nước.', 'tomAvatar.jpg', 'tomNSS.png', 'tomQR.png', 5);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (16, 'Nhái', 'nhái là loài có khả năng thay đổi màu sắc của da để hòa vào môi trường xung quanh. Điều này giúp chúng trở nên vô hình và tránh được sự phát hiện của các loài săn mồi. Bên cạnh đó, nhái cũng có khả năng tiết ra các chất độc từ da để tự vệ.', 'Nhái thường có một cơ thể tương đối nhỏ, với bốn chân và một cái đầu to. Lớp da của chúng thường mềm mại và ẩm ướt, với nhiều màu sắc khác nhau như xanh, nâu, đen hoặc có màu sọc. Đây là một trong những đặc điểm giúp chúng dễ dàng ẩn náu trong môi trường sống.', 'Nhái thường sinh sống ở các vùng ẩm ướt như sông, hồ, đầm lầy, rừng rậm và các khu vực ven nước khác, chủ yếu ở các vùng nhiệt đới và cận nhiệt đới. Chúng thường ẩn mình dưới các tảng đá, thân cây hoặc lớp thảm lá rơi để trú ẩn và tránh kẻ thù.', 'NhaiAvatar.jpg', 'nhaiNSS.png', 'nhaiQR.png', 6);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (17, 'Cóc', 'Con cóc là một loài động vật lưỡng cư độc đáo, có các đặc điểm sinh học và cấu trúc thích nghi tốt với môi trường sống nước ngọt và nước lợ, đóng vai trò quan trọng trong hệ sinh thái nơi chúng sinh sống.', 'Con cóc có thân hình hơi tròn, với một đôi chân dài và mềm mại. Da của chúng ẩm ướt và mịn màng, thích nghi tốt với môi trường nước. Màu sắc của con cóc thay đổi tùy thuộc vào loài và môi trường sống, từ xanh đến nâu, thường có các hoa văn hoặc sọc trên thân.', 'Con cóc sống trong môi trường nước ngọt như ao hồ, suối, sông và đầm lầy, cũng như trong môi trường nước lợ như rừng ngập mặn, đầm phá, và vùng đầm lầy ven biển', 'CocAvatar.jpg', 'cocNSS.png', 'cocQR.png', 6);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (18, 'Kỳ nhông', 'Kỳ nhông là loài có khả năng ẩn nấp và trà trộn rất hiệu quả trong môi trường sống. Với lớp da cứng, màu sắc phù hợp với môi trường, cùng với thói quen nằm im dưới nước, kỳ nhông có thể gần như biến mất trước mắt con mồi. Điều này giúp chúng dễ dàng bất ngờ tấn công các loài động vật khác.', 'Kỳ nhông là một loài bò sát có kích thước trung bình, với một cơ thể bệ vệ và một cái đầu rộng, chẳng giống loài cá sấu hung dữ. Chúng có một lớp da rắn chắc, thường có màu xám hoặc nâu, giúp chúng có thể ẩn nấp hiệu quả trong môi trường sống.', 'Kỳ nhông chủ yếu sinh sống ở các vùng nước ngọt như sông, hồ và đầm lầy ở các vùng nhiệt đới và cận nhiệt đới của châu Á, châu Phi và châu Mỹ La tinh. Chúng dành phần lớn thời gian nằm im dưới nước, chờ đợi các loài mồi như cá, chim, lưỡng cư và các loài động vật nhỏ khác bơi đến gần.', 'KyNhongAvatar.jpg', 'kynhongNSS.png', 'kynhongQR.png', 6);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (19, 'Cự đà(Rồng Nam Mỹ)', 'Cự đà (danh pháp khoa học Iguana) là một chi gồm các loài thằn lằn sống ở các khu vực nhiệt đới Trung và Nam Mỹ và khu vực Caribbe. Cự đà không tồn tại ở Việt Nam, mà chỉ được du nhập vào (chẳng hạn ở Thảo cầm viên Sài Gòn), do đó tên gọi kỳ nhông (động vật tồn tại ở Việt Nam) áp dụng cho cự đà là không đúng, gây lẫn lộn.', 'Cự đà còn được gọi là Rồng iguana, là một loài thằn lằn lớn thuộc họ Iguanidae, phân bố chủ yếu ở khu vực Nam Mỹ. Chúng có kích thước lớn, thường đạt chiều dài từ 1 đến 2 mét, bao gồm cả đuôi. Lưng của chúng thường có màu đỏ rực và có một loạt các gai nhỏ trên lưng và cổ, tạo nên hình ảnh mạnh mẽ và ấn tượng.', 'Cự đà  sống chủ yếu ở các vùng rừng mưa nhiệt đới và rừng cây thấp ẩm ướt của khu vực Nam Mỹ, bao gồm các quốc gia như Colombia, Venezuela, Ecuador, Peru, Bolivia và Brazil. Chúng thích sống ở những vùng rừng có cây cỏ và cây bụi dày đặc, nơi cung cấp nhiều nơi ẩn náu và thức ăn phong phú cho chúng.', 'cudaAvatar.jpg', 'cudaNSS.png', 'cudaQR.png', 1);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (20, 'Tắc kè bông', 'Tắc kè bông, còn được biết đến với tên gọi tiếng Anh là hedgehog, là một loài động vật có vỏ lông dày và nhọn, phần lớn được bao phủ bởi các lông mềm và rậm. Chúng có thóp lưng và thân hình nhỏ gọn, với đuôi ngắn. Đặc điểm đáng chú ý nhất của tắc kè bông là khả năng cuộn tròn thành một quả cầu khi gặp nguy hiểm.', 'Tắc kè bông có hình dáng nhỏ gọn với vỏ lông dày và nhọn, thường được phủ bởi các lông mềm và rậm. Chúng có thóp lưng, thân hình tròn và đuôi ngắn. Đặc điểm nổi bật nhất là khả năng cuộn tròn thành một quả cầu khi gặp nguy hiểm.', 'Tắc kè bông phân bố rộng rãi ở nhiều khu vực trên thế giới, đặc biệt là ở châu Âu, châu Á và châu Phi.', 'tackebongAvatar.jpg', 'tackebongNSS.png', 'tackebongQR.png', 1);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (21, 'Thằn lằn Komodo', 'Chúng có khả năng săn mồi mạnh mẽ và nhanh nhẹn, thường săn chủ yếu là các loài động vật lớn như lợn rừng và nai. Điều đặc biệt là thằn lằn Komodo cũng có khả năng tiêu hóa cả phần xương của con mồi, làm cho chúng trở thành một trong những loài săn mồi đáng sợ nhất trên trái đất.', 'Thằn lằn Komodo là loài thằn lằn lớn nhất thế giới, với thân hình to lớn và cơ bắp. Da của thằn lằn Komodo có màu xám hoặc nâu với các đốm đen rải rác. Đầu của thằn lằn Komodo khá lớn và có hàm răng sắc nhọn, là vũ khí chính để săn mồi. Chúng cũng có một cái lưỡi rất dài và linh hoạt.', 'Thằn lằn Komodo sống chủ yếu trên một số hòn đảo nhỏ thuộc quần đảo Komodo ở Indonesia. Thằn lằn Komodo thường mọc sống trong các khu rừng xanh và các vùng cỏ cây khô cằn trên các hòn đảo này.', 'komodoAvatar.jpg', 'komodoNSS.png', 'komodoQR.png', 1);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (22, 'Thằn lằn Gekko', 'Gekko là loài thằn lằn nhỏ có mắt lớn, khả năng leo trèo tốt và kháng kỳ diệu bằng việc tháo chạy đuôi. Chúng thích nghi với nhiều môi trường sống và thường được tìm thấy trong các khu vực đô thị.', 'Gekko là loài thằn lằn nhỏ, có thân hình mảnh mai và mắt lớn tròn. Chúng có khả năng leo trèo tốt trên các bề mặt phẳng và thậm chí là ngược dốc. Đặc điểm đặc biệt của gekko là khả năng tháo chạy đuôi khi gặp nguy hiểm, giúp chúng thoát khỏi kẻ săn mồi.', 'Gekko sống ở nhiều môi trường khác nhau trên toàn thế giới, từ rừng nhiệt đới đến khu vực đô thị. Chúng thích ẩn náu trong hang đá, hốc cây. Chúng có thể được tìm thấy ở nhiều khu vực trên thế giới, bao gồm các khu vực nhiệt đới ẩm ướt ở Đông Nam Á.', 'gekkoAvatar.jpg', 'canguNSS.png', 'canguQR.png', 1);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (23, 'Rùa biển', 'Rùa biển đóng vai trò quan trọng trong hệ sinh thái biển, ảnh hưởng đến cân bằng sinh thái và sự phát triển của các loài khác. Đồng thời, chúng cũng mang lại nhiều giá trị văn hóa và kinh tế cho các cộng đồng ven biển, từ lâu đã trở thành biểu tượng của sự bền vững và bảo tồn môi trường biển.', 'Rùa biển, với vẻ ngoài mạnh mẽ và phong cách biểu diễn bắt mắt, là loài động vật biển lớn có vỏ phẳng và trơn. Chúng thường có kích thước lớn và trọng lượng nặng, với vỏ màu xanh lá cây hoặc nâu đậm. Chân và vây được biến thành dạng chân bơi, giúp chúng di chuyển mạnh mẽ trong nước.', 'Rùa biển thường sống ở các vùng biển và đại dương trên khắp thế giới, từ các vùng nhiệt đới đến các vùng cận nhiệt đới và ôn đới. Chúng có thể được tìm thấy ở các bãi biển, rạn san hô, và các vùng biển khác, nơi chúng săn mồi và sinh sản. Đất nước nơi có rùa biển phụ thuộc vào loại hình môi trường biển mà chúng sống, và chúng có thể tồn tại ở một loạt các quốc gia trên toàn thế giới.', 'ruabienAvatar.jpeg', 'ruabienNSS.png', 'ruabienQR.png', 1);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (24, 'Rùa', 'Rùa là những động vật bò sát có vỏ sò cứng bảo vệ cơ thể. Chúng có đuôi phẳng và dài, chân chùm với móng vuốt mạnh mẽ. Rùa thường có khả năng ẩn náu trong vỏ sò khi gặp nguy hiểm và có tuổi thọ lâu dài, một số có thể sống hàng chục hoặc hàng trăm năm.', 'Rùa có hình dáng đặc trưng với vỏ sò cứng và lưng màu nâu hoặc xanh lá cây. Chúng có đầu nhỏ, mắt lớn và chân chùm mạnh mẽ. Rùa thường di chuyển chậm chạp và thường được biết đến với vẻ đẹp đậm chất cổ điển.', 'Rùa có thể được tìm thấy ở hầu hết các môi trường sống trên toàn thế giới, từ nước ngọt đến nước mặn và từ vùng nhiệt đới đến các khu vực cận cực. Tùy thuộc vào loài, rùa có thể sống trong các môi trường như rừng nhiệt đới, sa mạc, thảo nguyên, hồ và sông. Các quốc gia có sự đa dạng sinh học cao thường là nơi sinh sống của nhiều loài rùa, bao gồm Brasil, Costa Rica, Madagascar, Úc và Indonesia.', 'ruaAvatar.jpg', 'ruaNSS.png', 'ruaQR.png', 1);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (25, 'Cá hồi', 'Cá hồi là một loại cá thuộc họ Salmonidae, được biết đến với việc sống trong nước ngọt và biển. Đặc điểm nổi bật của chúng bao gồm việc có thể di chuyển từ nước ngọt ra biển và ngược lại để sinh sản.', 'Cá hồi thường có thân dài, mảnh mai với lớp vảy bóng loáng và màu sắc đa dạng từ xám đến xanh dương, thậm chí đến đỏ cam ở một số loài. Chúng có đầu nhỏ, mắt lớn và đuôi phân nhánh hình vây.', 'Cá hồi thường sống ở vùng nước lạnh của Bắc Đại Tây Dương và Thái Bình Dương, bao gồm cả sông nước ngọt và biển cả. Chúng thường di cư từ biển vào sông để đẻ trứng và sinh sản.', 'cahoiAvatar.jpg', 'cahoiNSS.png', 'cahoiQR.png', 2);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (26, 'Cá chép', 'Cá chép là một loại cá nước ngọt thường được biết đến với vẻ đẹp mạnh mẽ và màu sắc rực rỡ. Thân hình của chúng thường có dạng hình dẹp, vảy lấp lánh và các vây đẹp mắt. Đặc biệt, cá chép cũng được biết đến với sự chịu đựng và khả năng thích nghi với môi trường nước khác nhau.', 'Cá chép, một loại cá nước ngọt phổ biến, có những đặc điểm nổi bật như thân hình mạnh mẽ, vảy lấp lánh, và một bộ vây đẹp mắt. Chúng thường có màu sắc từ vàng đến cam, đôi khi có các đốm đen hoặc các sọc trắng trên cơ thể.', 'Cá chép thường sống ở các hồ, ao, và sông nước ngọt, đặc biệt là ở khu vực châu Á như Trung Quốc, Nhật Bản và các nước Đông Nam Á. Chúng thích môi trường nước lạnh và có nhiều đáy bãi, nơi chúng có thể tìm kiếm thức ăn và ẩn nấp.', 'cachepAvatar.jpg', 'cachepNSS.png', 'cachepQR.png', 2);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (27, 'Cá mập đầu búa', 'Cá mập đầu búa nổi bật với đặc điểm đầu dạng búa, giúp chúng tăng khả năng cảm nhận môi trường xung quanh. Đây là loài cá mập lớn, có thể đạt đến kích thước đáng kể và thường được tìm thấy trong các vùng nước ấm trên toàn thế giới. Chúng thường săn mồi ở vùng nước cạn và chú trọng vào loài cá lớn và các động vật biển khác.', 'Cá mập đầu búa có ngoại hình đặc trưng với đầu dạng búa, nổi bật với đôi mắt lớn nằm ở hai đầu của búa, tạo ra một lưng cong khi nhìn từ phía trên. Thân của chúng thường dẹp và mảnh mai, với lớp vảy mịn. Màu sắc của cá mập đầu búa thường là màu xám hoặc nâu, giúp chúng phản chiếu môi trường xung quanh khi săn mồi hoặc tránh kẻ săn mồi.', 'Cá mập đầu búa có thể được tìm thấy ở nhiều vùng biển trên thế giới, nhưng chủ yếu sống ở các khu vực nhiệt đới và cận nhiệt đới. Một số địa điểm phổ biến của chúng bao gồm vùng biển ở quần đảo Hawaii, vùng biển Caribbean, vùng biển gần bờ biển của châu Phi và Ấn Độ Dương.', 'camapdaubuaAvatar.jpg', 'camapdaubuaNSS.png', 'camapdaubuaQR.png', 2);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (28, 'Cá kiếm', 'Cá kiếm còn được biết đến với tên gọi là swordfish trong tiếng Anh, là một loài cá biển nổi tiếng với đặc điểm nổi bật là đầu hình kiếm sắc bén.', 'Cá kiếm có ngoại hình đặc trưng với thân hình mảnh mai và thon dài, giúp chúng di chuyển nhanh chóng trong nước. Đặc biệt, đỉnh đầu của cá kiếm được hình thành như một thanh kiếm sắc bén, từ đó xuất phát tên gọi của loài này.', 'Cá kiếm thường sống ở vùng biển ấm, đặc biệt là ở các khu vực nhiệt đới và cận nhiệt đới trên toàn thế giới. Chúng có thể được tìm thấy ở các khu vực biển nằm giữa vĩ độ 45°N và 45°S. Xuất hiện gần các bờ biển lục địa và các rặng san hô. Đất nước mà có thể tìm thấy cá kiếm bao gồm các quốc gia có bờ biển ấm như Hoa Kỳ', 'cakiemAvatar.jpg', 'cakiemNSS.png', 'cakiemQR.png', 2);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (29, 'Cá trích', 'Cá trích thường di cư theo đàn lớn và là mồi chính cho nhiều loài cá mập và chim biển. Chúng cũng được đánh bắt và sử dụng rộng rãi trong ngành công nghiệp thực phẩm, đặc biệt là để làm thành phần chính của mỡ cá herring và gia vị cho nhiều món ăn trên toàn thế giới.', 'Cá trích có ngoại hình đặc trưng với thân hình mảnh mai và dài, thường có chiều dài từ 20 đến 40 cm. Chúng có lớp vảy nhỏ và màu sắc thường là bạc hoặc xanh dương, có thể chuyển sang màu xám hoặc xanh lá cây ở một số loài.', 'Chúng thường di cư theo đàn lớn trong suốt mùa xuân và mùa hè để tìm kiếm thức ăn. Đất nước nơi cá herring phổ biến nhất bao gồm các quốc gia như Na Uy, Iceland, Canada, Nga, Thụy Điển và Đan Mạch', 'catrichAvatar.jpg', 'catrichNSS.png', 'catrichQR.png', 2);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (30, 'Cá Koi', 'Cá koi, loài cá được nuôi trong hồ cá hoặc hồ tường, nổi tiếng với vẻ đẹp đa dạng và màu sắc rực rỡ. Chúng được chăm sóc cẩn thận để phát triển ra những màu sắc và hoa văn độc đáo, tạo nên một phong cách thẩm mỹ riêng trong nghệ thuật nuôi cá.', 'Cá koi có ngoại hình đặc trưng với thân hình mảnh mai và dẹp, đuôi cong và vảy lớn. Một trong những điểm nổi bật của cá koi là màu sắc đa dạng và rực rỡ, từ màu đỏ, cam, vàng đến trắng, xanh lá cây và đen. Vảy của cá koi thường lấp lánh dưới ánh sáng, tạo ra một vẻ đẹp lộng lẫy khi nhìn từ xa.', 'Cá koi thường được nuôi trong hồ cá hoặc hồ tường trong các khu vườn hoặc khu chơi giải trí. Ban đầu, cá koi được tìm thấy ở Nhật Bản, nơi chúng được nuôi và coi là một biểu tượng của sự may mắn và tình cảm.', 'koiAvatar.jpg', 'koiNSS.png', 'koiQR.png', 2);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (31, 'Hồng hạc', 'Hồng hạc, loài chim biểu tượng của sự yên bình và thanh lịch, nổi tiếng với vẻ đẹp và đặc điểm nổi bật. Chim hồng hạc thường được coi là biểu tượng của sự thanh cao và tinh tế, thường xuất hiện trong văn hóa và nghệ thuật như một biểu tượng của sự thanh lịch và sự tinh tế.', 'Hồng hạc có ngoại hình đặc trưng với thân hình mảnh mai và cao, bộ lông mềm mại và màu trắng hoặc hồng. Mỏ của chúng dài và cong. Chân của hồng hạc thường dài và mảnh mai, giúp chúng điều khiển trong nước một cách linh hoạt và nhẹ nhàng.', 'Hồng hạc thường sinh sống ở các khu vực nước ngọt, như ao, hồ, đầm lầy, và các vùng đồng bằng có nước. Chúng cũng có thể được tìm thấy ở các khu vực đầm lầy ven biển và vùng đồng cỏ lớn. Bao gồm cả các nước ở châu Âu, Bắc Mỹ, Châu Á và Úc.', 'honghacAvatar.jpg', 'honghacNSS.png', 'honghacQR.png', 3);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (32, 'Cú', 'Cú là một loài chim có kích thước trung bình, thân hình mảnh mai và đôi chân dài. Mỏ của cú thường dài và nhọn, phù hợp cho việc săn mồi, trong khi đôi chân dài và mảnh mai giúp chúng di chuyển nhanh chóng trên mặt đất hoặc trong không khí.', 'Cú là một loài chim có ngoại hình đặc trưng với thân hình mảnh mai và đôi chân dài. Lông của cú thường có màu đen hoặc nâu, thường đi kèm với một số điểm trắng hoặc sọc trắng tinh tế trên cánh và lưng.', 'Cú thường sinh sống ở các khu vực mở, bao gồm đồng cỏ, cánh đồng, đầm lầy, và các khu vực mở rộng khác. Chúng có thể được tìm thấy ở nhiều vùng địa lý trên thế giới, bao gồm cả châu Âu, Bắc Mỹ, Châu Á, châu Phi và Úc.', 'cuAvatar.jpg', 'cuNSS.png', 'cuQR.png', 3);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (33, 'Chim sẻ', 'Chim sẻ, loài chim nhỏ gọn thuộc họ Passeridae, nổi tiếng với bộ lông màu nâu hoặc xám pha trắng trên cánh và đuôi. Chúng thích ẩn mình trong bụi cây hoặc tìm thức ăn trên mặt đất.', 'Chim sẻ thường có ngoại hình nhỏ gọn, với bộ lông màu nâu hoặc xám, thường pha trắng ở cánh và đuôi. Mỏ của chim sẻ ngắn và hơi dày, thích hợp cho việc ăn hạt và thức ăn nhỏ.', 'Chim sẻ sinh sống ở nhiều môi trường khác nhau. Chúng thích ẩn mình trong bụi cây, hang đá hoặc tìm kiếm thức ăn trên mặt đất, thường trong nhóm nhỏ. Chim sẻ phổ biến trên toàn thế giới, từ châu Âu đến châu Á, châu Phi, châu Mỹ và Úc.', 'seAvatar.jpg', 'seNSS.png', 'chimseQR.png', 3);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (34, 'Chim quạ', 'Chim quạ, còn được gọi là bói cá, là loài chim săn mồi rất thông minh và linh hoạt. Chúng có đôi mắt sắc bén và mỏ nhọn, giúp chúng săn mồi hiệu quả trên bầu trời hoặc trên mặt đất.', 'Chim quạ thường có ngoại hình mảnh mai và thon dài, với bộ lông màu nâu hoặc xám pha trắng tạo ra các mảng vằn và đốm tương phản.', 'Chim quạ có thể được tìm thấy ở nhiều loại môi trường khác nhau, từ vùng đồng cỏ mở rộng đến khu rừng cây rậm và thậm chí là trong các khu dân cư. Chim quạ phổ biến tại các quốc gia bao gồm Hoa Kỳ,...', 'quaAvatar.jpg', 'quaNSS.png', 'chimquaQR.png', 3);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (35, 'Chim bồ câu', 'Chim bồ câu, còn được biết đến là biểu tượng của sự bình yên và tình yêu. Chúng thường được tìm thấy ở nhiều khu vực đô thị và nông thôn, gắn bó với con người trong nhiều thế kỷ, thể hiện sự gần gũi và hòa bình giữa loài người và thiên nhiên.', 'Chim bồ câu thường có ngoại hình to lớn, thân hình tròn trịa và cánh rộng lớn. Bộ lông của chúng thường màu xám hoặc trắng, với những điểm nhấn như vòng cổ màu đen và cánh với các vằn màu. Chân của chim bồ câu thường ngắn, phù hợp cho việc đi bộ trên mặt đất.', 'Chim bồ câu phân bố rộng rãi trên khắp thế giới, từ các khu vực nông thôn đến các thành phố lớn. Một số loài chim bồ câu có nguồn gốc từ châu Âu, châu Á, châu Phi và châu Mỹ.', 'bocauAvatar.jpg', 'bocauNSS.png', 'chimbocauQR.png', 3);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (36, 'kền kền', 'Kền kền, chim nước lớn thuộc họ Threskiornithidae,nổi bật với hình dáng thon dài và cổ cong đặc trưng. Kền kền thường di chuyển chậm rãi và có thể thấy chúng đứng thẳng trong nước, với đôi chân dài giúp chúng săn mồi dưới nước một cách hiệu quả.', 'Kền kền thường có hình dáng mảnh mai với thân hình thon dài và cổ cong. Bộ lông của chúng thường có màu trắng hoặc xám pha lẫn với màu đen, tạo ra các đốm và vằn đặc trưng.', 'Kền kền thường sống ở gần các khu vực nước ngọt hoặc nước lợ như hồ, ao, sông, đầm lầy và bãi bồi ngập nước. Chúng phân bố trên khắp các châu lục, từ châu Phi, châu Á, châu Mỹ đến châu Âu và Úc.', 'kenkenAvatar.jpg', 'kenkenNSS.png', 'kenkenQR.png', 3);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (37, 'Thú mỏ vịt', 'Đúng vậy, thú mỏ vịt (Ornithorhynchus anatinus) là một loài động vật có vú đẻ trứng bán thuỷ sinh đặc hữu của miền đông Úc, bao gồm cả Tasmania. Thú mỏ vịt có thể được nhìn thấy ở các vùng đất ven sông, nơi chúng xây tổ và săn mồi như tôm, ốc, và các loài côn trùng sống dưới nước.', 'Thú mỏ vịt có đầu nhỏ, hơi nghiêng về màu nâu đậm và đen. Mũi dài và mềm, giống mỏ vịt. Thân hình thẳng như một tấm gỗ để dễ dàng lướt đi trong nước.Thú mỏ vịt có bốn ngón chân, mỗi ngón chân có một đốm trắng.', 'Thú mỏ vịt, là một loài động vật có bộ lông dày và vú giống như lông, nhưng lại có mỏ giống vịt và chân bơi giống bắp cày. Loài này sinh sống chủ yếu ở Úc, đặc biệt là trong các khu vực có sông, suối và hồ nước ngọt trong các vùng rừng và thảo nguyên.', 'thumovitAvatar.jpg', 'thumovitNSS.png', 'thumovitQR', 4);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (38, 'Gấu trúc', 'Gấu trúc là một loài động vật có vú sống ở châu Á, được biết đến với vẻ ngoài đáng yêu và tính cách ôn hòa. Gấu trúc thường được mô tả là ôn hòa và nhút nhát, tuy nhiên, chúng có thể trở nên hung dữ nếu cảm thấy bị đe dọa hoặc bị xâm phạm lãnh thổ.', 'Gấu trúc có hình dạng tròn trịa, với bộ lông dày mịn, thường màu đen và trắng. Đặc điểm nổi bật nhất của gấu trúc là sự hiện diện của mặt nạ màu đen quanh mắt và tai. Gấu trúc thường có kích thước nhỏ đến trung bình, thường nặng từ 70 đến 160 kg, tùy thuộc vào loài và giới tính.', 'Gấu trúc thường sống ở các khu rừng núi, khu rừng đất thấp và khu vực cây bụi ẩm ướt ở châu Á. Chúng có thể được tìm thấy từ miền đông Ấn Độ, Trung Quốc, miền đông Nga, đến miền đông của Himalaya và Đông Nam Á.', 'gautrucAvatar.jpg', 'gautrucNSS.png', 'gautrucQR.png', 4);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (39, 'Cá heo', 'Cá heo thuộc họ Cetacean, cùng với cá voi và các loài động vật biển khác. Có nhiều loài cá heo khác nhau trên thế giới, bao gồm cá heo đi biển, cá heo hồng, cá heo xanh, và nhiều loài khác', 'Cá heo có hình dạng giống cá, có vây đuôi và vòi hô hấp ở trên đầu. Chúng có thân hình thon dài, màu sắc thường là xám hoặc xanh dương, và có các vết màu trắng hoặc xám trên cơ thể.', 'Cá heo phân bố khắp các đại dương trên thế giới.Vịnh California, Hoa Kỳ: Vịnh California là một trong những vùng biển nổi tiếng với số lượng cá heo ấn tượng, đặc biệt là loài cá heo đi biển (Tursiops truncatus). Cá heo đi biển ở đây thường thấy trong các bầy lớn và thường tương tác tích cực với tàu thuyền và du khách', 'caheoAvatar.jpg', 'caheoNSS.png', 'caheoQR.png', 4);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (40, 'Tê giác', 'Tê giác là một trong những loài động vật lớn nhất và đáng yêu nhất trên thế giới, đặc biệt nổi tiếng với việc sở hữu một chiếc sừng lớn trên mũi.Tê giác thuộc họ tê giác (Rhinocerotidae) và có khoảng 5 loài khác nhau, trong đó ba loài chính là tê giác Phi, tê giác Ấn Độ và tê giác Java. Các loài còn lại là tê giác Đông Nam Á và tê giác Sumatra, đều đang đối mặt với nguy cơ tuyệt chủng.', 'Tê giác thường có hình dạng to lớn với cơ thể mạnh mẽ và chân ngắn. Đặc điểm nổi bật nhất của tê giác là chiếc sừng lớn trên mũi, được tạo thành từ chất sừng. Trong số các loài tê giác, tê giác Phi và tê giác Ấn Độ có hai chiếc sừng, trong khi tê giác Java, tê giác Đông Nam Á và tê giác Sumatra chỉ có một chiếc sừng.', 'Tê giác thường sống ở các vùng rừng, thảo nguyên và cánh đồng ở châu Phi và châu Á. Chúng phân bố rộng rãi từ Nam Phi, qua các quốc gia châu Phi như Kenya, Tanzania, Zimbabwe, cho đến Ấn Độ, Nepal, Indonesia và Việt Nam.', 'tegiacAvatar.jpg', 'tegiacNSS.png', 'tegiacQR.png', 4);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (41, 'Voi', 'Voi là một loài động vật có vú lớn thuộc họ Elephantidae và là một trong những loài động vật đặc trưng của các khu vực rừng nhiệt đới và cận nhiệt đới trên thế giới. Voi là loài động vật thông minh và xã giao. Chúng thường sống theo đàn, với một con đực lãnh đạo và một số con cái và con non khác', 'Voi là một động vật có hình dáng ấn tượng, với cơ thể to lớn và mạnh mẽ. Chúng có da dày, màu xám hoặc xám nâu, thường có những nếp gấp đặc trưng. Điều đặc biệt nhất ở voi là vòi dài và linh hoạt, có thể dài đến hai mét', 'Châu Phi là nơi có nhiều loài voi châu Phi (Loxodonta africana) sống tự nhiên nhất. Các quốc gia như Kenya, Tanzania, Nam Phi, Zimbabwe và Botswana đều có dân số voi lớn. Các khu vực như Vườn quốc gia Serengeti và Vườn quốc gia Kruger là nơi mà bạn có thể tìm thấy một lượng lớn các đàn voi châu Phi.', 'voiAvatar.jpg', 'voiNSS.png', 'voiQR.png', 4);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (42, 'Dơi', 'Dơi là một loài động vật có vú thuộc bộ Dơi (Chiroptera), là nhóm động vật duy nhất có khả năng bay thực sự. Dơi có thể sống ở nhiều môi trường khác nhau, từ rừng nhiệt đới đến sa mạc và khu đô thị', 'Dơi có hình dáng và kích thước đa dạng, từ nhỏ như ngón tay đến lớn như cừu. Chúng có cơ thể được phủ lớp lông mềm mại và có sải cánh lớn, giúp chúng bay một cách linh hoạt. Một số loài dơi cũng có màng cánh nằm giữa các chi để giúp chúng bay.', 'Dơi thường sống ở các khu rừng. Rừng mưa Amazon: Với môi trường rừng mưa nhiệt đới lớn nhất thế giới, Amazon là nơi sinh sống của nhiều loài dơi, bao gồm cả các loài dơi trái cây và dơi lá.Rừng mưa Costa Rica: Costa Rica nổi tiếng với sự đa dạng sinh học của mình, và rừng mưa ở đây cũng là nhà của nhiều loài dơi khác nhau.', 'doiAvatar.jpg', 'doiNSS.png', 'doiQR.png', 4);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (43, 'Bọ cánh cứng', 'Bọ cánh cứng là một nhóm động vật không xương sống có ba đôi chân phân nhánh và cơ thể được chia thành đầu, ngực và bụng. Chúng có khả năng thích ứng với nhiều môi trường sống và có vai trò quan trọng trong hệ sinh thái.', 'Bọ cánh cứng có cơ thể được chia thành ba phần: đầu, ngực và bụng. Đầu thường có mắt phức hợp, cặp râu và miệng có thể chứa các bộ phận nhai hoặc hút. Ngực thường có hai cặp cánh và ba đôi chân. Bụng thường có hình dạng và màu sắc đa dạng, phụ thuộc vào loài.', 'Bọ cánh cứng phân bố rộng khắp trên toàn thế giới, từ các môi trường nhiệt đới ẩm ướt đến các vùng ôn đới khô cằn. Chúng có thể được tìm thấy trên mặt đất, trong đất, trên cây, dưới nước, và trong các môi trường sống khác nhau', 'bocanhcungAvatar.jpg', 'bocanhcungNSS.png', 'bocanhcungQR.png', 5);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (44, 'Bọt biển', 'Bọt biển, hay hải sắc, là một nhóm động vật không xương sống có cấu trúc đa tế bào đặc biệt. Sự tái sinh nhanh chóng giúp chúng thích ứng với môi trường biển đa dạng. Chúng đóng vai trò quan trọng trong hệ sinh thái đại dương bằng cách cung cấp nơi ẩn náu và thức ăn cho nhiều loài khác.', 'Ngoại hình của bọt biển thường là một cấu trúc đa dạng và phong phú. Chúng có thể xuất hiện dưới dạng các tế bào không có cấu trúc rõ ràng, tạo ra hình dạng linh hoạt và đa dạng. Màu sắc của bọt biển có thể đa dạng từ trắng, vàng, cam đến xanh, tím, đỏ và thậm chí là đen.', 'Bọt biển có thể được tìm thấy ở hầu hết các vùng biển trên thế giới, từ các vùng biển nhiệt đới ấm áp đến các vùng biển ôn đới lạnh giá. Chúng sinh sống ở các môi trường biển nước mặn, từ khu vực ven bờ đến phần sâu của đại dương. Bọt biển cũng tồn tại trong các môi trường nước ngọt như hồ, sông, và ao.', 'botbienAvatar.jpg', 'botbienNSS.png', 'botbienQR.png', 5);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (45, 'San hô', 'San hô là nhóm động vật biển không xương sống với cấu trúc đa dạng, từ những chiếc phủ nhỏ đến rạn san hô lớn. Chúng thường bao gồm các polyp nhỏ gắn vào một khung xương vững chắc. San hô quan trọng với hệ sinh thái biển và là một trong những môi trường sống giàu dinh dưỡng nhất trên Trái Đất.', 'San hô có ngoại hình đa dạng, từ những cụm nhỏ đến rạn san hô lớn. Chúng thường có màu sắc rực rỡ và đa dạng, từ xanh dương đến đỏ và cam. Cấu trúc chính của chúng là các polyp nhỏ gắn vào một khung xương canxi cacbonat.', 'San hô thường sống ở vùng nước ấm ẩm trên toàn thế giới, chủ yếu tập trung ở các khu vực biển nhiệt đới và ôn đới. Các quốc gia và vùng lãnh thổ có rạn san hô phổ biến bao gồm Australia, Ấn Độ Dương, Thái Bình Dương, vùng Caribe, và Đông Phi.', 'sanhoAvatar.jpg', 'sanhoNSS.png', 'sanhoQR.png', 5);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (46, 'Sâu bướm', 'Sâu bướm là giai đoạn phát triển của bướm trước khi chúng trưởng thành, thường có cơ thể dài và uốn cong để ẩn nấp trong môi trường sống. Chúng thường tiêu hủy lá, hoa, hoặc thân cây trong quá trình phát triển. Khi trưởng thành, sâu bướm thường tiến hóa thành bướm và tham gia vào quá trình sinh sản.', 'Sâu bướm thường có hình dạng dài và uốn cong, phù hợp cho việc ẩn nấp trong môi trường sống của chúng. Cơ thể thường mềm mại và màu sắc đa dạng, phụ thuộc vào loài. Chúng thích nghi với nhiều loại thức ăn khác nhau, từ lá đến hoa và thậm chí thân cây.', 'Sâu bướm có thể sống ở nhiều nơi khác nhau, phụ thuộc vào loài và cách sống của chúng. Một số sâu bướm sống trong đất, ẩn nấp dưới lá hoặc trong thân cây, trong khi những loài khác có thể sống ở mặt đất hoặc trong môi trường nước ngọt.', 'saubuomAvatar.jpg', 'saubuomNSS.png', 'saubuomQR.png', 5);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (47, 'ỐC sên', 'Ốc sên, hay còn được gọi là sên, là loài động vật không xương sống có vỏ để bảo vệ cơ thể. Chúng di chuyển bằng cách nhảy hoặc trượt trên một lớp dịch nhầy. Mặc dù đa dạng về hình dáng và màu sắc, ốc sên thường có cơ thể mềm mại và vỏ cứng, với một đôi cánh nhỏ để bảo vệ mình khỏi các mối nguy hiểm.', 'Ốc sên thường có cơ thể mềm mại và vỏ cứng, có thể có nhiều màu sắc và hoa văn khác nhau. Chúng di chuyển bằng cách trượt trên một lớp dịch nhầy và có thể có một đôi cánh nhỏ. Đa dạng hình dáng và màu sắc của ốc sên tùy thuộc vào loài và môi trường sống.', 'Ốc sên có thể sống ở nhiều môi trường khác nhau, bao gồm cả đất liền và môi trường nước. Chúng thường được tìm thấy trong vườn, rừng, cánh đồng, khu vực đáy đồng cỏ và cả trong môi trường nước ngọt hoặc nước mặn.', 'ocsenAvatar.jpg', 'ocsenNSS.png', 'ocsenQR.png', 5);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (48, 'Đỉa', 'Đỉa, một loại sâu bọ nhỏ, thường có cơ thể màu đen hoặc nâu và dẹp. Chúng thường sống trong đất và gây hại cho cây trồng bằng cách ăn rễ và thân. Đỉa có vai trò quan trọng trong việc phân hủy và cải tạo đất, nhưng cũng có thể gây ra tổn thương đáng kể đối với nông nghiệp và vườn cây.', 'Đỉa thường có hình dạng dẹp và màu sắc đa dạng, từ màu đen đến nâu. Cơ thể của chúng nhỏ và dẹp, giúp chúng dễ dàng di chuyển trong đất. Đặc điểm này cũng giúp chúng tránh sự chú ý của kẻ săn mồi và bảo vệ khỏi các mối nguy hiểm.', 'Đỉa thường sống dưới lòng đất, trong các vùng đất ẩm ướt và giàu dinh dưỡng. Chúng cũng có thể được tìm thấy trong các khu vực có thảm cây, cỏ hoặc rác thối, nơi cung cấp điều kiện lý tưởng cho sự phát triển và hoạt động của chúng.Đỉa phân bố khắp nơi trên thế giới, từ vùng nhiệt đới đến cận cực. Chúng sống ở mọi loại đất, từ đất phèn đến đất sét, và có thể được tìm thấy ở mọi châu lục trên Trái Đất.', 'diaAvatar.jpg', 'diaNSS.png', 'diaQR.png', 5);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (49, 'Kỳ giông Mexico (Ambystoma mexicanum)', 'Kỳ giông Mexico (Ambystoma mexicanum), còn được biết đến với tên gọi axolotl, có những đặc điểm nổi bật đáng chú ý. Loài này nổi tiếng với khả năng tái sinh tuyệt vời, có thể phục hồi và tái tạo các cơ quan và mô trong trường hợp bị tổn thương.', 'Axolotl thường có hình dáng độc đáo, với cơ thể mảnh mai, chân và đuôi phát triển dài. Chúng có da mịn màng với các vảy mềm trên bề mặt. Màu sắc của axolotl có thể đa dạng từ màu sáng như trắng, vàng, cam đến màu đậm như đen, xám, hoặc nâu, và thường có các mảng hoặc đốm màu khác nhau trên cơ thể.', 'Kỳ giông Mexico (Ambystoma mexicanum), hay axolotl, sống tự nhiên ở các hồ nước ngọt, ao, và kênh rạch trong các vùng nước ấm ẩm của Mexico. Đây là loài động vật sống cảm thấy thoải mái ở nhiệt độ môi trường từ 14 đến 20 độ C (57 đến 68 độ F).', 'kygiongAvatar.jpg', 'kygiongNSS.png', 'kygiongQR.png', 6);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (50, 'Sa giông xương sườn nhọn (Pleurodeles waltl)', 'Sa giông xương sườn nhọn (Pleurodeles waltl) nổi bật với khả năng tái sinh các cơ quan và mô, là một trong những loài có khả năng này. Chúng cũng thích nghi tốt với môi trường nước ngọt đa dạng và có thói quen ăn động vật nhỏ, nhờ màu sắc và hình dáng giúp chúng săn mồi hiệu quả dưới nước.', 'Sa giông có các nốt sần chạy dọc hai bên. Thông qua đó, các xương sườn sắc nhọn của nó có thể đâm thủng. Các xương sườn hoạt động như một cơ chế phòng thủ, ít gây hại cho sa giông. Cơ chế này có thể coi là một hệ thống tiêm nọc độc nguyên thủy và thô sơ nhưng hoàn toàn vô hại với con người.', 'Sa giông xương sườn nhọn (Pleurodeles waltl) thường sống ở các vùng nước ngọt, bao gồm các hồ, suối, và ao. Chúng được tìm thấy chủ yếu ở khu vực phía tây nam châu Âu, bao gồm Tây Ban Nha, Bồ Đào Nha và miền nam Pháp.', 'sagiongAvatar.jpeg', 'sagiongNSS.png', 'sagiongQR.png', 6);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (51, 'Cóc biển (Marine Toad)', 'Cóc biển, hay còn gọi là Marine Toad hoặc Bufo marinus, là một loài cóc lớn có nguồn gốc từ Trung và Nam Mỹ. Tuy nhiên, chúng đã được giới thiệu và lan rộng rất nhiều ở các khu vực khác trên thế giới', 'Cóc biển là một loài có kích thước lớn trong họ cóc, với các con đực lớn có thể đạt đến chiều dài hơn 20 cm, trong khi con cái thường lớn hơn. Chúng có thân hình to, mập mạp, màu nâu hoặc xám với vằn sáng tạo thành các mẫu vẩy', 'Úc: Cóc biển đã được giới thiệu vào Úc vào cuối thế kỷ 19 nhằm kiểm soát sâu bọ làm hại cho nông nghiệp. Tuy nhiên, chúng đã trở thành một loài xâm lấn nghiêm trọng ở nước này, đặc biệt là ở miền Bắc và miền Đông của đất nước.', 'cocbienAvatar.jpg', 'cocbienNSS.png', 'cocbienQR.png', 6);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (52, 'Cóc mía(Cane Toad)', 'Cane Toad, hay còn được gọi là cóc mía, có tên khoa học là Rhinella marina (trước đây là Bufo marinus), là một loài cóc lớn có nguồn gốc từ Trung và Nam Mỹ. Tuy nhiên, chúng đã được giới thiệu và lan rộng rất nhiều ở các khu vực khác trên thế giới, bao gồm cả Úc và các đảo trong Thái Bình Dương.', 'Cane Toad là một loài cóc lớn, thân hình mập mạp, màu nâu hoặc xám, thường có các đốm đen hoặc vằn. Đầu to, mắt lớn, và có một đốm màu vàng hoặc đỏ ở giữa. Chúng có bộ chân mạnh mẽ và da thô ráp.', 'Quần đảo Caribe: Các đảo trong khu vực Caribe cũng là nơi chúng sinh sống phổ biến, với các quốc gia như Cuba, Jamaica và Puerto Rico thường ghi nhận sự hiện diện của chúng.', 'cocmiaAvatar.jpg', 'cocmiaNSS.png', 'cocmiaQR.png', 6);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (53, 'Ếch cây xanh', 'Ếch cây xanh, còn được gọi là ếch lá, có tên khoa học là Hyla cinerea, là một loài ếch thuộc họ Ếch cây (Hylidae). Đây là một loài ếch phổ biến tại Bắc Mỹ, thường được tìm thấy ở các khu vực có môi trường sống phong phú như rừng, bãi cỏ và vùng đầm lầy.', 'Ếch cây xanh có màu sắc thường là màu xanh lá cây, nhưng cũng có thể có các tông màu khác như xám hoặc nâu. Chúng thường có các vạch màu xanh nhạt hoặc trắng trên thân và chân.Kích thước: Thường thì ếch cây xanh có kích thước nhỏ đến trung bình, với chiều dài từ 3 đến 5 centimet vài lúc có thể lên đến 7 centimet.', 'Miền Nam và Miền Đông Hoa Kỳ: Đây là một trong những vùng phân bố phổ biến nhất của loài ếch cây xanh. Chúng sống nhiều ở các bang như Florida, Georgia, South Carolina và Texas, nơi có môi trường ẩm ướt và khí hậu ấm áp.', 'echcayxanhAvatar.jpg', 'echcayxanhNSS.png', 'echcayxanhQR.png', 6);
INSERT IGNORE INTO `animals` (`id_animal`, `name`, `gioi_thieu_text`, `ngoai_hinh_text`, `noi_sinh_song_text`, `avatar`, `noi_sinh_song_image`, `imgqr3d`, `classanimals_id`) VALUES (54, 'Ếch độc vàng(Golden Poison Frog)', 'Golden Poison Frog, hoặc còn gọi là Phyllobates terribilis, là một trong những loài ếch độc mạnh nhất trên Trái Đất. Chúng sinh sống chủ yếu ở rừng mưa ẩm ướt của Colombia', 'Da của loài ếch này chứa các độc tố mạnh mẽ, chủ yếu là batrachotoxins, có thể gây tổn thương hoặc thậm chí là tử vong đối với các kẻ săn mồi. Batrachotoxins có tác dụng chống lại cơ chế của natri trong cơ thể, gây ra các vấn đề về truyền dẫn xung điện và gây ra sự mất khả năng di chuyển.', 'Vùng Chocó là một trong những vùng rừng mưa nhiệt đới đa dạng sinh học nhất trên Trái Đất, nơi có môi trường lý tưởng cho sự phát triển và sinh sống của Golden Poison Frog. Đây là khu vực có lượng mưa lớn hàng năm và nhiệt độ ấm áp quanh năm', 'echdocvangAvatar.jpg', 'echdocvangNSS.png', 'echdocvangQR.png', 6);

-- INSERT IGNORE listanimals
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (1, 'CaSauList1.jpg', 1);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (2, 'CaSauList2.jpg', 1);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (3, 'CaSauList3.jpg', 1);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (4, 'ThanLanList1.jpg', 2);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (5, 'ThanLanList2.jpg', 2);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (6, 'ThanLanList3.jpg', 2);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (7, 'RanList1.jpg', 3);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (8, 'RanList2.jpg', 3);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (9, 'RanList3.jpg', 3);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (10, 'CaNguList1.jpg', 4);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (11, 'CaNguList2.jpg', 4);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (12, 'CaNguList3.jpg', 4);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (13, 'CaMapList1.jpg', 5);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (14, 'CaMapList2.jpg', 5);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (15, 'CaMapList3.jpg', 5);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (16, 'CalocList1.jpg', 6);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (17, 'CalocList2.jpg', 6);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (18, 'CalocList3.jpg', 6);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (19, 'ChimCanhCutList1.jpg', 7);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (20, 'ChimCanhCutList2.jpg', 7);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (21, 'ChimCanhCutList3.jpg', 7);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (22, 'DaiBangList1.jpg', 8);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (23, 'DaiBangList2.jpg', 8);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (24, 'DaiBangList3.jpg', 8);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (25, 'BoNongList1.jpg', 9);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (26, 'BoNongList2.jpg', 9);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (27, 'BoNongList3.jpg', 9);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (28, 'HoList1.jpg', 10);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (29, 'HoList2.jpg', 10);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (30, 'HoList3.jpg', 10);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (31, 'GauList1.png', 11);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (32, 'GauList2.jpeg', 11);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (33, 'GauList3.jpg', 11);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (34, 'HuouCaoCoList1.jpg', 12);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (35, 'HuouCaoCoList2.jpg', 12);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (36, 'HuouCaoCoList3.jpg', 12);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (37, 'SuaList1.jpg', 13);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (38, 'SuaList2.jpg', 13);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (39, 'SuaList3.jpg', 13);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (40, 'BachtuotLitst1.jpg', 14);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (41, 'BachtuotLitst2.jpg', 14);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (42, 'BachtuotLitst3.jpg', 14);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (43, 'TomList1.jpg', 15);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (44, 'TomList2.jpg', 15);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (45, 'TomList3.jpg', 15);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (46, 'NhaiList1.jpg', 16);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (47, 'NhaiList2.jpg', 16);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (48, 'NhaiList3.jpg', 16);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (49, 'CocList1.jpg', 17);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (50, 'CocList2.jpg', 17);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (51, 'CocList3.jpg', 17);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (52, 'KynhongList1.jpg', 18);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (53, 'KynhongList2.jpg', 18);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (54, 'KynhongList3.jpg', 18);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (55, 'RuaBienList1.jpg', 23);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (56, 'RuaBienList2.jpg', 23);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (57, 'RuaBienList3.jpeg', 23);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (58, 'RuaList1.jpg', 24);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (59, 'RuaList2.jpg', 24);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (60, 'RuaList3.jpg', 24);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (61, 'CuDaList1.jpeg', 19);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (62, 'CuDaList2.jpg', 19);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (63, 'CuDaList3.jpg', 19);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (64, 'TacKeBongList1.jpg', 20);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (65, 'TacKeBongList2.jpg', 20);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (66, 'TacKeBongList3.jpg', 20);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (67, 'KomodoList1.jpg', 21);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (68, 'KomodoList2.jpeg', 21);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (69, 'KomodoList3.jpg', 21);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (70, 'GekkoList1.jpg', 22);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (71, 'GekkoList2.jpg', 22);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (72, 'GekkoList3.jpg', 22);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (73, 'CaHoiList1.jpg', 25);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (74, 'CaHoiList2.jpg', 25);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (75, 'CaHoiList3.jpg', 25);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (76, 'CaChepList1.jpg', 26);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (77, 'CaChepList2.jpg', 26);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (78, 'CaChepList3.jpg', 26);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (79, 'CaMapDauBuaList1.jpg', 27);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (80, 'CaMapDauBuaList2.jpg', 27);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (81, 'CaMapDauBuaList3.jpg', 27);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (82, 'CaKiemList1.jpg', 28);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (83, 'CaKiemList2.jpg', 28);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (84, 'CaKiemList3.jpg', 28);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (85, 'CaTrichList1.jpg', 29);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (86, 'CaTrichList2.jpg', 29);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (87, 'CaTrichList3.jpg', 29);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (88, 'KoiList1.jpg', 30);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (89, 'KoiList2.jpg', 30);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (90, 'KoiList3.jpeg', 30);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (91, 'HongHacList1.jpg', 31);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (92, 'HongHacList2.jpg', 31);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (93, 'HongHacList3.jpg', 31);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (94, 'CuList1.jpg', 32);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (95, 'CuList2.jpg', 32);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (96, 'CuList3.jpg', 32);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (97, 'SeList1.jpg', 33);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (98, 'SeList2.jpg', 33);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (99, 'SeList3.jpg', 33);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (100, 'QuaList1.jpg', 34);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (101, 'QuaList2.jpg', 34);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (102, 'QuaList3.jpg', 34);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (103, 'BoCauList1.jpg', 35);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (104, 'BoCauList2.jpg', 35);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (105, 'BoCauList3.jpg', 35);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (106, 'KenKenList1.jpeg', 36);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (107, 'KenKenList2.jpg', 36);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (108, 'KenKenList3.jpg', 36);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (109, 'ThuMoVitList1.jpg', 37);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (110, 'ThuMoVitList2.jpg', 37);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (111, 'ThuMoVitList3.jpg', 37);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (112, 'GauTrucList1.jpeg', 38);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (113, 'GauTrucList2.jpg', 38);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (114, 'GauTrucList3.jpg', 38);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (115, 'CaHeoList1.jpg', 39);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (116, 'CaHeoList2.jpg', 39);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (117, 'CaHeoList3.jpg', 39);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (118, 'TeGiacList1.jpg', 40);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (119, 'TeGiacList2.jpg', 40);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (120, 'TeGiacList3.jpg', 40);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (121, 'VoiList1.jpg', 41);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (122, 'VoiList2.jpg', 41);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (123, 'VoiList3.jpg', 41);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (124, 'DoiList1.jpg', 42);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (125, 'DoiList2.jpg', 42);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (126, 'DoiList3.jpg', 42);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (127, 'BoCanhCungList1.jpg', 43);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (128, 'BoCanhCungList2.jpg', 43);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (129, 'BoCanhCungList3.jpg', 43);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (130, 'BotBienList1.jpg', 44);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (131, 'BotBienList2.jpg', 44);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (132, 'BotBienList3.jpg', 44);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (133, 'SanHoList1.jpg', 45);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (134, 'SanHoList2.jpg', 45);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (135, 'SanHoList3.jpg', 45);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (136, 'SauBuomList1.jpg', 46);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (137, 'SauBuomList2.jpg', 46);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (138, 'SauBuomList3.jpg', 46);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (139, 'OcSenList1.jpg', 47);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (140, 'OcSenList2.jpg', 47);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (141, 'OcSenList3.jpg', 47);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (142, 'DiaList1.jpg', 48);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (143, 'DiaList2.jpg', 48);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (144, 'DiaList3.jpg', 48);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (145, 'KyGiongList1.jpg', 49);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (146, 'KyGiongList2.jpg', 49);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (147, 'KyGiongList3.jpg', 49);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (148, 'SaGiongList1.jpg', 50);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (149, 'SaGiongList2.jpg', 50);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (150, 'SaGiongList3.jpg', 50);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (151, 'CocBienList1.jpg', 51);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (152, 'CocBienList2.jpg', 51);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (153, 'CocBienList3.jpg', 51);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (154, 'CocMiaList1.jpg', 52);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (155, 'CocMiaList2.jpg', 52);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (156, 'CocMiaList3.jpg', 52);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (157, 'EchCayXanhList1.jpg', 53);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (158, 'EchCayXanhList2.jpg', 53);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (159, 'EchCayXanhList3.jpg', 53);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (160, 'EchDocVangList1.jpg', 54);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (161, 'EchDocVangList2.jpg', 54);
INSERT IGNORE INTO `listanimals` (`id`, `animalimage`, `animals_id`) VALUES (162, 'EchDocVangList3.jpg', 54);

SET FOREIGN_KEY_CHECKS = 1;
